backend:
  name: git-gateway
  repo: master
media_folder: static/assets
public_folder: assets
collections:
  - name: menu-item
    label: Menu Item
    folder: markdown-pages/menu-item
    create: true
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: menu-item,
        }
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, required: true }
      - { name: body, label: Body, widget: markdown, required: true }

  - name: service
    label: Service
    folder: markdown-pages/service
    create: true
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: service,
        }
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, required: true }
      - { name: body, label: Body, widget: markdown, required: true }

  - name: equity
    label: Equity
    folder: markdown-pages/equity
    create: true
    fields:
      - {
          name: templateKey,
          label: Template Key,
          widget: hidden,
          default: equity,
        }
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, required: true }
      - { name: body, label: Body, widget: markdown, required: true }
