backend:
  name: git-gateway
  repo: master
media_folder: static/assets
public_folder: assets
collections:
  - name: menu
    label: Menu Pages
    folder: menu-pages
    create: true
    fields:
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, required: true }
      - {
          name: category,
          label: Category,
          widget: select,
          options: ["menu item", "services", "property", "blog"],
          required: true,
        }
      - { name: body, label: Body, widget: markdown, required: true }

  - name: services
    label: Services
    folder: services
    create: true
    fields:
      - { name: path, label: Path, required: true }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, required: true }
      - {
          name: category,
          label: Category,
          widget: select,
          options: ["menu item", "services", "property", "blog"],
          required: true,
        }
      - { name: body, label: Body, widget: markdown, required: true }
